baseURL = "http://localhost:1313"
title = "My AI-Powered Hugo Site"
languageCode = "en-us"
enableRobotsTXT = true

# Multilingual Support
defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageCode = "en"
    contentDir = "content/en"
    title = "My AI Hugo Site (EN)"
    weight = 1
  [languages.es]
    languageCode = "es"
    contentDir = "content/es"
    title = "Mi Sitio Hugo con AI (ES)"
    weight = 2
  [languages.fr]
    languageCode = "fr"
    contentDir = "content/fr"
    title = "Mon Site Hugo avec AI (FR)"
    weight = 3
  [languages.de]
    languageCode = "de"
    contentDir = "content/de"
    title = "Meine AI Hugo Seite (DE)"
    weight = 4

# Sitemap & SEO
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Image Processing
[imaging]
  quality = 75
  anchor = "center"

# Markup Configuration (Markdown Processing)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "dracula"

# Permalinks
[permalinks]
  blog = "/blog/:slug/"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

relativeURLs = true
uglyURLs = false